# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample_Wiki_SearchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  # Pods for Sample_Wiki_SearchApp

  target 'Sample_Wiki_SearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sample_Wiki_SearchAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
